### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by EdCharbeneau** [budcribar/RemoteBlazorWebView#12]
I'm always amazed at what the Blazor community comes up with. This sounds really cool.

My initial thoughts are:

- How secure is it? I think you may need some docs explaining how this is secure, or "why should I trust it?".
- I got a little confused with how the "UI is shared over the browser". Is the UI being shared a Web UI or WPF UI?
- Screen shots would be helpful, or even a short video or gif.

**Comment by budcribar** [comment]
The security depends on what is implemented in the server. The project contains a server that can be compiled with no security (for demo purposes) or with Azure B2C security. There is a demo server hosted at https://server.remoteblazorwebview.org using Azure B2C authentication which can be used for demo purposes. Real world applications would need to host their own server in the cloud and use whatever authentication is appropriate for the use-case.

The UI is based on the Blazor WebView Controls (Wpf and WinForms) which basically do a diff on the HTML DOM and send the differences to the embedded web browser control. When running in the remote mode, the differences are sent to a server which then in turn send them to a browser.  Bottom line is the user will see the HTML rendered in their web browser even though the WPF app is running on a remote system (even if it is behind a firewall).

Thanks for the suggestions on the video and screen shots. I will work on that and also a couple of diagrams.
